DEBUG = false
POEM_PER_PAGE = 50
SEARCH_RESULT_PER_PAGE = 8
USER_FETCH_COUNT = 10
TOKEN = ""
TEST_TOKEN = ""
ADMIN_CHAT_ID = 0
OUD_FILES_CHANNEL_ID = 0
MAX_FAVORITE = 150
MAX_FAVORITE_PER_PAGE = 15
WEBHOOK_URL = ""
WEBHOOK_SECRET_TOKEN = ""
OUD_MUSIC_CHANNEL_ID = 0

SENTRY_TOKEN = ""
SENTRY_HOST = ""
SENTRY_ID = 0

DB_HOST = "localhost"
DB_PORT = 5432
DB_NAME = "oud"
DB_USER = ""
DB_PASSWORD = ""

ES_HOST = "http://localhost:9200"
ES_API_KEY = ""
ES_INDEX_NAME = "oud"
ES_SYNC_CHUNK_SIZE = 1000
ES_SYNC_KEEP_INDICES = 2
ES_SYNC_LOCK_KEY = 6072026001

REDIS_HOST = "localhost"
REDIS_PORT = 6379
REDIS_PASSWORD = ""
